class Aerospace < Formula
  desc "AeroSpace is an i3-like tiling window manager for macOS"
  homepage "https://github.com/0xACE/AeroSpace"
  url "https://github.com/0xACE/AeroSpace/archive/refs/tags/v0.20.4-Beta.tar.gz"
  version "0.20.4-Beta"
  # After pushing the tag, recompute with:
  #   curl -sL https://github.com/0xACE/AeroSpace/archive/refs/tags/v0.20.4-Beta.tar.gz | shasum -a 256
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  depends_on xcode: ["16.3", :build] # Swift 6.3+ required
  depends_on macos: :ventura

  def install
    # The committed xcodeproj has snapshot version and a non-existent cert identity.
    # Both are overridden via xcodebuild build settings below.
    # The two generated Swift source files are patched directly.
    (buildpath/"Sources/Common/versionGenerated.swift").write <<~SWIFT
      // FILE IS GENERATED BY generate.sh
      public let aeroSpaceAppVersion = "#{version}"
    SWIFT

    (buildpath/"Sources/Common/gitHashGenerated.swift").write <<~SWIFT
      // FILE IS GENERATED BY generate.sh
      public let gitHash = "v#{version}"
      public let gitShortHash = "v#{version}"
    SWIFT

    # Build the universal CLI binary via Swift Package Manager
    system "swift", "build",
      "-c", "release",
      "--arch", "arm64",
      "--arch", "x86_64",
      "--product", "aerospace"

    # Ad-hoc sign the CLI binary
    system "codesign", "-s", "-", ".build/apple/Products/Release/aerospace"

    # Build the GUI app via Xcode, overriding the committed cert identity with
    # ad-hoc signing ("-") and injecting the real version into the Info.plist
    system "xcodebuild",
      "-scheme", "AeroSpace",
      "-destination", "generic/platform=macOS",
      "-configuration", "Release",
      "-derivedDataPath", ".xcode-build",
      "CODE_SIGN_IDENTITY=-",
      "CODE_SIGN_STYLE=Manual",
      "CODE_SIGNING_REQUIRED=YES",
      "CODE_SIGNING_ALLOWED=YES",
      "MARKETING_VERSION=#{version}"

    bin.install ".build/apple/Products/Release/aerospace"
    prefix.install ".xcode-build/Build/Products/Release/AeroSpace.app"
  end

  def post_install
    # Symlink the app bundle into /Applications. Uses opt_prefix so the symlink
    # survives brew upgrades without needing to be recreated.
    system "ln", "-sfn", "#{opt_prefix}/AeroSpace.app", "/Applications/AeroSpace.app"
  end

  def caveats
    <<~EOS
      AeroSpace.app is symlinked into /Applications from:
        #{opt_prefix}/AeroSpace.app

      On first launch, macOS will prompt for Accessibility permissions.

      To remove the /Applications entry on uninstall:
        rm /Applications/AeroSpace.app
    EOS
  end

  test do
    assert_predicate bin/"aerospace", :executable?
  end
end
